### ISSUE TITLE
Workers keep getting killed

### ISSUE THREAD

**Issue by aspiring-engineer** [LimeDrive/ygg-rss-proxy#16]
Salut !

Super projet, j'avais fais un script de mon côté mais le tien est carrément plus complet !

Néanmoins j'ai un problème récurrent, soit mes workers se font timeout, soit SIGKILL. J'ai check j'ai largement assez de CPU et de RAM pour le faire fonctionner.
Au delà de ça, j'ai pas mal d'erreurs similaires à #4 alors que j'ai bien tout configuré.

**Ma conf**: 
```yaml
  yggratio-flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: yggratio-flaresolverr
    networks:
      yggratio-network:
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    restart: always

  yggratio-yggproxy:
    image: ghcr.io/limedrive/ygg-rss-proxy:latest
    container_name: yggratio-yggproxy
    networks:
      yggratio-network:
    environment:
        YGG_USER: ${YGG_USER}
        YGG_PASS: ${YGG_PASS}
        RSS_HOST: yggratio-yggproxy
        RSS_PORT: 5000
        RSS_SHEMA: http
        FLARESOLVERR_HOST: yggratio-flaresolverr
        FLARESOLVERR_SHEMA: http
        FLARESOLVERR_PORT: 8191
        GUNICORN_PORT: 5000
        LOG_LEVEL: DEBUG
    restart: always
    depends_on:
        - yggratio-flaresolverr
```

**Exemples de logs:**

```log
2024-06-14T19:50:30.011665+0000 INFO ygg_basic_login Successfully authenticated to YGG
2024-06-14T19:50:30.012280+0000 DEBUG ygg_cloudflare_login Session cookies: <CookieJar[<Cookie cf_clearance=XXXX for .ygg.re/>, <Cookie ygg_=XXXXXX for .ygg.re/>]>
2024-06-14T19:50:30.016907+0000 DEBUG _new_conn Starting new HTTPS connection (1): www.ygg.re:443
2024-06-14T19:50:35.724742+0000 DEBUG _make_request https://www.ygg.re:443 "GET /rss?action=generate&type=subcat&id=2183&********
[2024-06-14 19:50:39 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:31)
[2024-06-14 19:50:40 +0000] [1] [ERROR] Worker (pid:31) was sent SIGKILL! Perhaps out of memory?
[2024-06-14 19:50:40 +0000] [35] [INFO] Booting worker with pid: 35
``` 

```
2024-06-14T19:18:31.638570+0000 DEBUG _make_request https://www.ygg.re:443 "GET /rss?action=generate&type=subcat&id=2184&********
[2024-06-14 19:18:36 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:12)
[2024-06-14 19:18:37 +0000] [1] [ERROR] Worker (pid:12) was sent SIGKILL! Perhaps out of memory?
[2024-06-14 19:18:37 +0000] [17] [INFO] Booting worker with pid: 17
2024-06-14T19:25:55.321712+0000 DEBUG _new_conn Starting new HTTPS connection (1): www.ygg.re:443
[2024-06-14 19:25:56 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:17)
[2024-06-14 19:25:57 +0000] [1] [ERROR] Worker (pid:17) was sent SIGKILL! Perhaps out of memory?
[2024-06-14 19:25:57 +0000] [18] [INFO] Booting worker with pid: 18
2024-06-14T19:25:58.414919+0000 DEBUG _new_conn Starting new HTTPS connection (1): www.ygg.re:443
2024-06-14T19:26:09.380631+0000 DEBUG _make_request https://www.ygg.re:443 "GET /auth/login HTTP/1.1" 403 None
2024-06-14T19:26:10.356895+0000 INFO ygg_login Cloudflare is enabled, using FlareSolverr
2024-06-14T19:26:11.173063+0000 DEBUG _new_conn Starting new HTTP connection (1): yggratio-flaresolverr:8191
2024-06-14T19:26:11.319947+0000 DEBUG _make_request http://yggratio-flaresolverr:8191 "GET / HTTP/1.1" 200 172
[2024-06-14 19:26:27 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:15)
[2024-06-14 19:26:28 +0000] [1] [ERROR] Worker (pid:15) was sent SIGKILL! Perhaps out of memory?
[2024-06-14 19:26:28 +0000] [19] [INFO] Booting worker with pid: 19
2024-06-14T19:26:32.999958+0000 DEBUG _new_conn Starting new HTTPS connection (1): www.ygg.re:443
2024-06-14T19:26:40.036645+0000 DEBUG _make_request https://www.ygg.re:443 "GET /auth/login HTTP/1.1" 403 None
2024-06-14T19:26:40.447775+0000 INFO ygg_login Cloudflare is enabled, using FlareSolverr
2024-06-14T19:26:40.451967+0000 DEBUG _new_conn Starting new HTTP connection (1): yggratio-flaresolverr:8191
2024-06-14T19:26:40.456729+0000 DEBUG _make_request http://yggratio-flaresolverr:8191 "GET / HTTP/1.1" 200 172
[2024-06-14 19:26:58 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:16)
[2024-06-14 19:26:59 +0000] [1] [ERROR] Worker (pid:16) was sent SIGKILL! Perhaps out of memory?
2024-06-14T19:26:59.736896+0000 DEBUG _new_conn Starting new HTTPS connection (1): www.ygg.re:443
[2024-06-14 19:27:00 +0000] [20] [INFO] Booting worker with pid: 20
```

```
[2024-06-14 19:16:31 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:9)
[2024-06-14 19:16:32 +0000] [1] [ERROR] Worker (pid:9) was sent SIGKILL! Perhaps out of memory?
[2024-06-14 19:16:32 +0000] [13] [INFO] Booting worker with pid: 13
2024-06-14T19:16:33.035337+0000 DEBUG _get_conn Resetting dropped connection: www.ygg.re
2024-06-14T19:16:33.480692+0000 DEBUG _make_request https://www.ygg.re:443 "GET /auth/login HTTP/1.1" 403 None
2024-06-14T19:16:33.482903+0000 INFO ygg_login Cloudflare is enabled, using FlareSolverr
2024-06-14T19:16:33.485263+0000 DEBUG _new_conn Starting new HTTP connection (1): yggratio-flaresolverr:8191
2024-06-14T19:16:33.490211+0000 DEBUG _make_request http://yggratio-flaresolverr:8191 "GET / HTTP/1.1" 200 172
[2024-06-14 19:17:02 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
[2024-06-14 19:17:02 +0000] [8] [ERROR] Error handling request /rss?action=generate&type=subcat&id=2178&passkey=XXXXX
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 878, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1253, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ygg_rss_proxy/app.py", line 34, in before_request
    init_session()
  File "/app/ygg_rss_proxy/session_manager.py", line 33, in init_session
    new_session()
  File "/app/ygg_rss_proxy/session_manager.py", line 15, in new_session
    ygg_session = ygg_login()
                  ^^^^^^^^^^^
  File "/app/ygg_rss_proxy/auth.py", line 150, in ygg_login
    return ygg_cloudflare_login(session, ygg_playload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ygg_rss_proxy/auth.py", line 74, in ygg_cloudflare_login
    response = fs_solver.request_get(url="https://www.ygg.re")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ygg_rss_proxy/fspy/solver.py", line 198, in request_get
    return self._do_the_work_for_get_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ygg_rss_proxy/fspy/solver.py", line 157, in _do_the_work_for_get_post
    response = self.req_session.post(self.flare_solverr_url, json=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1395, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-14 19:17:03 +0000] [8] [INFO] Worker exiting (pid: 8)
[2024-06-14 19:17:03 +0000] [1] [ERROR] Worker (pid:8) was sent SIGKILL! Perhaps out of memory?
[2024-06-14 19:17:03 +0000] [14] [INFO] Booting worker with pid: 14
```

Bref, une fois sur deux les requêtes ne passent pas. Merci pour le coup de main !

**Comment by LimeDrive** [comment]
Bonjour, 

- J'ai augmenté le timeout de GUnicorn, comme ça on verra ce que ça donne. 
- Voir le docker-compose avec ta configuration, j'ai rajouté un expose du port 5000 étant donné que tu n'utilise pas celui du conteneur par défaut. J'ai aussi mappé le dossier config de l'intérieur du conteneur. Car la base de données est dans le container avec ta configuration , c'est possible que ce soit ça qui provoque le timeout. Donc soit on la met dans un volume, soit tu la mets sur ton système comme dans l'exemple.
- J'ai aussi changé l'image sur :develop Tu bénéficieras des derniers fixes, notamment vis-à-vis de la base de données et du log qui est maintenant totalement offusqué. ( cookies, pass, id, passkey )

```yaml
version: '3.8'

services:

  yggratio-flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: yggratio-flaresolverr
    networks:
      - yggratio-network
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: Europe/Paris
    restart: always

  yggratio-yggproxy:
    image: ghcr.io/limedrive/ygg-rss-proxy:develop
    container_name: yggratio-yggproxy
    expose:
      - 5000
    volumes:
      - ./config:/app/config
    environment:
      TZ: Europe/Paris
      YGG_USER: ${YGG_USER}
      YGG_PASS: ${YGG_PASS}
      RSS_HOST: yggratio-yggproxy
      RSS_PORT: 5000
      FLARESOLVERR_HOST: yggratio-flaresolverr
      GUNICORN_PORT: 5000
      LOG_LEVEL: DEBUG
    networks:
      - yggratio-network
    restart: always
    depends_on:
      - yggratio-flaresolverr
 ```
 l'image devrait être déployée d'ici quelques minutes

**Comment by LimeDrive** [comment]
Je n'arrive pas à reproduire, même en bastonnant les workers sur les même requêtes en simultané.
https://gist.github.com/LimeDrive/fbfd8ef4acb0222723a0a57f53d25813

Ça a l'air d'être assez lié au système quand même. Peux-tu me donner les détails de ton système sur lequel est le container ? que je vois dans les prochains jours à monter une machine avec les mêmes specs.

Par ailleurs, on peut aussi essayer de réduire de moitié le nombre de workers. en ajoutant la variables d'environnement : 
`GUNICORN_WORKERS: 2`

j'ai poussé ce matin un update de l'image `:latest` sur la #18

**Comment by LimeDrive** [comment]
Le time out est déjà sur 2 minutes. Donc c'est qu'il y a soit une fonction qui bloque quelque part, soit un problème au niveau du système. 
Tu pourras pull la`:develop` dans quelques minutes. J'ai ajouté des exceptions par timeout dans le code afin d'essayer d'identifier se qui fait crash les worker. 
Je ferai les tests dans la semaine sur une machine à peu près comme la tienne pour voir si ça vient de là.

**Comment by LimeDrive** [comment]
Ha c'est peut être de l'IO's sur HDD pour la db. Du coup normalement c'est pas bien grave, sa vas levé une exception c'est tout. Tu n'a pas de worker kill par contre ici.

>j'ai 4 flux RSS différents pour YGG

oui j'ai fait les test avec 8 Flux appelé en même temps en reprenant tes subcat, et je ne rencontre pas le souci, mais sur ARM et une machine récente et puissante, donc pas comparable.

Je reprendrai les test dans quelque jours.

**Comment by LimeDrive** [comment]
Ok, je vois. 

Mettre un jitter sur les requêtes n'est pas forcément pertinent étant donné qu'elles seront décalées tout en même temps à part à faire du random. 

Sachant maintenant d'où vient le problème des workers qui se kill. J'ai mis un rétry sur les fonctions et une exclusion de l'erreur. Donc normalement, sa aura le même effet.

Alors j'ai pu tester personnellement en ddos mon instance. Pour avoir une remonté d'erreur. Ça a l'air concluant. 

Comme d'habitude, le fix et poussé sur la « :develop ». Je te laisse tester et me confirmer si le problème est résolu. Ensuite je ferai un update de l'image de base.

**Comment by LimeDrive** [comment]
C'est bien push en auto par le ci quand j'ai commit sur la branche dev. Donc c'est que cela n' a pas fonctionné pour toi.
A chaque fois il faudra faire un docker compose pull pour récup les nouvelle image. Je vais mettre un versioning dans le logs pour que je puisse vérifier que l'on est bien sur la bonne image develop a chaque fois.
Je n' ai pas réussi à reproduire de lock mais une IO error avec la db. Et il m'a fallu envoyer plus d' une centaine de requêtes en simultané pour l'avoir et c'est fix avec se que j'ai push.
Franchement je ne sais pas se qui bloque chez toi, donc il va falloir que  j'essaie sur VM avec différents config pour reproduire et debug. Vu le log de ton côté, l'exception ne passe pas par le prasser que j'ai mis en place c'est qu'elle sort directement de flask_session je suppose.
J'essaierai de lisser au max tout les appels db et la gestion des erreurs se soir en plus des ajustements.

**Comment by LimeDrive** [comment]
Bon je pousse une dernière tentative pour se soir afin de réglé ton souci.
Ajoute un timeout plus conséquent sur la base de données. De mon côté, même quand je force le test, Je n'ai plus aucune erreur. je n'ai réussi à la reproduire qu'une seule fois et là maintenant je n'y arrive plus.
ça va être mis directement sur la développe donc docker compose pull obligatoire. Il y a maintenant le numéro de version dans le log. le fixe et sur la 1.2.10 à bien vérifier quand tu lances ton conteneur. 

 Voici une vidéo du forcing sans résolution pour éviter de me faire taper sur les doigts car je ne suis pas certain que le site d'YGG apprécie mdr. Tu vois que de mon côté, ça tient quand même très bien. 

https://github.com/LimeDrive/ygg-rss-proxy/assets/82819873/45f89fb0-b15e-4bc6-a639-492defb75218
